"use client";

import { useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL;

interface Source {
  clause_ref: string;
  filename: string;
  project: string;
  similarity: number;
}

interface Result {
  query: string;
  answer: string;
  sources: Source[];
}

export default function Home() {
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit() {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch(`${API}/chat/quick`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query,
          project: null,
          top_k: 5,
        }),
      });

      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data = await res.json();
      setResult(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  }

  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "40px 20px" }}>

      {/* Header */}
      <h1 style={{ marginBottom: 4 }}>SCL Protocol Assistant</h1>
      <p style={{ color: "#666", fontSize: 14, marginBottom: 16 }}>
        Powered by the <strong>SCL Delay and Disruption Protocol 2nd Edition (2017)</strong>
      </p>

      {/* Nav */}
      <nav style={{ marginBottom: 24, display: "flex", gap: 20 }}>
        <a href="/" style={{ fontSize: 14, color: "#111", fontWeight: 600 }}>Quick Question</a>
        <a href="/conversation" style={{ fontSize: 14, color: "#666" }}>Conversation Mode</a>
      </nav>

      {/* Demo disclaimer */}
      <div style={{
        padding: "12px 16px",
        backgroundColor: "#fffbea",
        border: "1px solid #f0e68c",
        borderRadius: 6,
        fontSize: 12,
        color: "#666",
        marginBottom: 12,
        lineHeight: 1.6,
      }}>
        <strong>Demo purposes only.</strong> Answers are generated by <strong>GPT-4o mini</strong> using
        retrieval-augmented generation (RAG) over the SCL Protocol. Responses may be incomplete or
        inaccurate — always verify against the original document. This is not legal advice.
        For higher accuracy, this tool can be upgraded to use <strong>GPT-4o</strong> or <strong>o1</strong>.
      </div>

      {/* Copyright disclaimer */}
      <div style={{
        padding: "12px 16px",
        backgroundColor: "#f0f0f0",
        border: "1px solid #ddd",
        borderRadius: 6,
        fontSize: 12,
        color: "#666",
        marginBottom: 28,
        lineHeight: 1.6,
      }}>
        <strong>Copyright notice.</strong> The SCL Delay and Disruption Protocol 2nd Edition (2017) is
        published by and copyright of the{" "}
        <a href="https://www.scl.org.uk" target="_blank" rel="noopener noreferrer" style={{ color: "#444" }}>
          Society of Construction Law (UK)
        </a>
        . This tool is a non-commercial demonstration only and is not affiliated with or endorsed by the SCL.
        It does not reproduce the Protocol in full. Users are encouraged to obtain the official document
        directly from{" "}
        <a href="https://www.scl.org.uk/resources/delay-disruption-protocol" target="_blank" rel="noopener noreferrer" style={{ color: "#444" }}>
          scl.org.uk
        </a>
        .
      </div>

      {/* Question input */}
      <div style={{ marginBottom: 12 }}>
        <label style={{ display: "block", marginBottom: 4, fontWeight: 500, fontSize: 14 }}>
          Ask a question about the SCL Protocol
        </label>
        <textarea
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="e.g. What is the definition of concurrent delay? What methods of delay analysis are recommended?"
          rows={3}
          style={{
            width: "100%",
            padding: "10px 12px",
            fontSize: 14,
            borderRadius: 6,
            border: "1px solid #ccc",
            resize: "vertical",
            boxSizing: "border-box",
          }}
        />
        <p style={{ fontSize: 12, color: "#999", marginTop: 4 }}>
          Press Enter to submit · Shift+Enter for new line
        </p>
      </div>

      <button
        onClick={handleSubmit}
        disabled={loading || !query.trim()}
        style={{
          padding: "10px 24px",
          fontSize: 14,
          fontWeight: 600,
          backgroundColor: loading ? "#999" : "#111",
          color: "#fff",
          border: "none",
          borderRadius: 6,
          cursor: loading ? "not-allowed" : "pointer",
        }}
      >
        {loading ? "Searching..." : "Ask"}
      </button>

      {/* Error */}
      {error && (
        <div style={{
          marginTop: 24,
          padding: 16,
          backgroundColor: "#fff0f0",
          border: "1px solid #ffcccc",
          borderRadius: 6,
          color: "#cc0000",
          fontSize: 13,
        }}>
          {error}
        </div>
      )}

      {/* Result */}
      {result && (
        <div style={{ marginTop: 32 }}>
          <div style={{
            padding: 20,
            backgroundColor: "#f9f9f9",
            borderRadius: 8,
            border: "1px solid #e5e5e5",
            lineHeight: 1.7,
            whiteSpace: "pre-wrap",
            fontSize: 14,
          }}>
            {result.answer}
          </div>

          <div style={{ marginTop: 16 }}>
            <p style={{ fontWeight: 600, marginBottom: 8, fontSize: 13 }}>Sources</p>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {result.sources.map((s, i) => (
                <div key={i} style={{
                  padding: "8px 12px",
                  backgroundColor: "#f0f0f0",
                  borderRadius: 6,
                  fontSize: 12,
                  display: "flex",
                  justifyContent: "space-between",
                }}>
                  <span><strong>Section {s.clause_ref}</strong> — {s.filename}</span>
                  <span style={{ color: "#888" }}>{(s.similarity * 100).toFixed(1)}% match</span>
                </div>
              ))}
            </div>
          </div>

          <p style={{ fontSize: 11, color: "#aaa", marginTop: 16 }}>
            Answers are based on retrieved sections of the SCL Protocol and generated by GPT-4o mini.
            Always verify against the original document.
          </p>
        </div>
      )}
    </main>
  );
}